name: Build cross platform

permissions:
  contents: write

# Controls when the action will run. Triggers the workflow on push
on: 
  push:
  pull_request:
  release:
    # tags:
    # - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows",
            os: windows-latest,
            artifact: win-x64,
            ext: exe,
          }
        - {
            name: "Ubuntu",
            os: ubuntu-latest,
            artifact: linux-x64,
            ext: AppImage,
          }
        - {
            name: "MacOS",
            os: macos-latest,
            artifact: mac-arm64,
            ext: dmg,
          }

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Print env
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}

      - name: Install and Build
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: |
          npm ci
          npm run build
          npm run dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./dist/Goon*.dmg
            ./dist/Goon*.exe
            ./dist/Goon*.AppImage
          name: Goon-${{ matrix.config.artifact }}.${{ matrix.config.ext }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/Goon*.dmg
            ./dist/Goon*.exe
            ./dist/Goon*.AppImage
            ./dist/Goon*.snap

